# Generated by Django 5.1.7 on 2025-04-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='Descricao',
            new_name='descricao',
        ),
    ]
