# Generated by Django 5.2.1 on 2025-07-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
